// baet-web-vuejs/src/components/LinkMeta.vue
<template>
  <v-card flat class="align-content-center">
    <!-- <v-card-title></v-card-title> -->
    <v-card-text>
      <v-container fluid class="pa-0">

        <v-layout row wrap>
          <v-flex>
            <v-btn
                v-for="simple_link in linkData.simple_links"
                :key="simple_link"
                color="blue-grey"
                class="white--text"
                :href="simpleLinks[simple_link]"
                target="_blank"
              >
              <!-- :href="prepareUrl(simple_link)" -->
              {{ simple_link }}
              <v-icon right dark>launch</v-icon>
            </v-btn>
            <v-btn
                color="blue-grey"
                class="white--text"
                :href="shortLink"
                target="_blank"
            >
              {{ linkData['short_link'] }}
              <v-icon right dark>launch</v-icon>
            </v-btn>
          </v-flex>

          <v-flex xs12>
            <v-btn flat icon
                   :href=linkData.long_link
                   target="_blank"
            >
              <v-icon>link</v-icon>
            </v-btn>
            <span style="font-size: xx-small; font-style: italic">
              {{ linkData.long_link }}
            </span>
          </v-flex>
        </v-layout>
      </v-container>
    </v-card-text>

    <v-card-text>
      <qrcode
          :value=prepareUrl()
          :options="{ size: 128 }" />
    </v-card-text>

    <v-card-actions>

      <!-- COPY -->
      <v-btn fab dark color="primary"
             v-clipboard:copy="prepareUrl()"
             v-clipboard:success="onCopyOk(prepareUrl())"
             v-clipboard:error="onCopyError(prepareUrl())">
        <v-icon dark>file_copy</v-icon>
      </v-btn>
      <!--
      <v-btn fab dark color="primary"
             @click="doCopy(prepareUrl())">
        <v-icon dark>file_copy</v-icon>
      </v-btn>
      -->

      <!-- STATS -->
      <v-btn v-if="!isSingleItem"
          fab dark color="indigo"
          :href="'/links/'+linkData['short_link']"
      >
        <v-icon dark>timeline</v-icon>
      </v-btn>

      <!-- SHARE -->
      <!--
      <v-btn fab dark color="teal">
        <v-icon dark>share</v-icon>
      </v-btn>
      -->
      <LinkShare
          :linkData="linkData"
        />

    </v-card-actions>

    <v-card-text>
      <LinkStats v-if="isSingleItem"
                 :linkId="linkData['_id']"
      />
    </v-card-text>

    <v-snackbar
        v-model="snackbar.active"
        :timeout="snackbar.timeout"
        :color="snackbar.color"
        bottom multi-line
    >
      <h3>{{ snackbar.text }}</h3>
      <v-btn
          flat
          @click="snackbar.active = false"
      >
        <v-icon medium>close</v-icon>
      </v-btn>
    </v-snackbar>

    <v-card-text v-if=isDev>
      linkData...<br/> {{ linkData }}
      <br/> isSingleItem: {{isSingleItem}}
    </v-card-text>
  </v-card>
</template>

<style lang="scss" scoped>
  /* .md-card {
    width: 800px;
    margin: 4px;
    display: inline-block;
    vertical-align: top;
  } */
</style>

<script>
  /* eslint-disable */
  import { myConfig, isDev } from '@/app-config'; // eslint-disable-line
  import LinkStats from '@/components/LinkStats';
  import LinkShare from '@/components/LinkShare';
  import VueQrcode from '@xkeshi/vue-qrcode';
  const diz = this;

  export default {
    name: "LinkMeta",
    data: () => ({
      isDev: isDev,
      snackbar: {
        active: false,
        timeout: 2000,
        color: 'info',
        text: ''
      },
    }),
    components: {
      qrcode: VueQrcode,
      LinkStats,
      LinkShare
    },
    props: {
      isSingleItem: Boolean,
      linkData: Object
    },
    computed: {
      shortLink() {
        return myConfig.web.baseUrl + this.linkData['short_link'];
      },
      simpleLinks() {
        let sLinks = {};
        this.linkData['simple_links'].forEach((simple_link) => {
          sLinks[simple_link] = myConfig.web.baseUrl+simple_link;
        });
        //console.log(JSON.stringify(sLinks));
        return sLinks;
      }
    },
    methods: {
      prepareUrl: function(val) {
        let theUrl = '';
        theUrl += myConfig.web.baseUrl; //'https://baet.no/';
        if (val) {
          theUrl += val;
        }
        else {
          theUrl += this.linkData['short_link'];
        }

        //console.log(theUrl)
        return theUrl;
      },
      onCopyOk: function(inData) {
        if (isDev) {
          //-console.log('onCopyOk... copied OK!!! -> ' + inData)
        }

        this.snackbar.text = this.$t('resources.links.buttons.copy.confirm') + inData;
        this.snackbar.color = 'success';
        this.snackbar.active = true;
      },
      onCopyError: function(inData) {
        if (isDev) {
          //-console.log('onCopyError... ERROR!!! -> ' + inData)
        }
      },
      doCopy: function(inData) {
        this.$copyText(inData).then(
            function(e) { // OK
              if (isDev) {
                //-console.log('doCopy... copied OK!!! -> ' + inData)
              }

              diz.snackbar.text = this.$t('resources.links.buttons.copy.confirm') + inData;
              diz.snackbar.color = 'success';
              diz.snackbar.active = true;
            },
            function(e) { // FAIL // eslint-disable-line
              if (isDev) {
                //-console.log('doCopy... ERROR!!!')
              }
            }
        );
      }
    }
  }
</script>

// ulink-web-reactjs/src/links/LinkMeta.jsx
import React, { Component } from 'react';

import QRCode from 'qrcode.react'; // https://github.com/zpao/qrcode.react
import {CopyToClipboard} from 'react-copy-to-clipboard'; // https://github.com/nkbt/react-copy-to-clipboard

import TimeAgo from 'react-timeago'; // https://github.com/nmn/react-timeago
import norStrings from 'react-timeago/lib/language-strings/no';
import engStrings from 'react-timeago/lib/language-strings/en';
import timeAgoBuildFormatter from 'react-timeago/lib/formatters/buildFormatter';

import { toast } from 'react-toastify'; // https://github.com/fkhadra/react-toastify

import Button from '@material-ui/core/Button';
import IconCopy from '@material-ui/icons/FileCopy';
import IconTimeline from '@material-ui/icons/Timeline';
import IconLink from '@material-ui/icons/Link';
import IconSchedule from '@material-ui/icons/Schedule';

import Card from '@material-ui/core/Card';
import CardActions from '@material-ui/core/CardActions';
import CardContent from '@material-ui/core/CardContent';

import { Container, Row, Col } from 'react-grid-system';

import SimpleLinks from './SimpleLinks';
import SocialShareButtons from './SocialShareButtons';

import { appConfig, isDev } from './../common/AppConfig';
import { translator } from './LinkAssets';

const timeAgoFormatter_nor = timeAgoBuildFormatter(norStrings);// eslint-disable-line
const timeAgoFormatter_eng = timeAgoBuildFormatter(engStrings);

const styles = {
  main: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    width: 800,
    //minHeight: 600,
    margin: '0.2em',
    display: 'inline-block',
    verticalAlign: 'top',
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
};

class LinkMeta extends Component {
  constructor(props) {
    super(props);
    this.handleOnCopy = this.handleOnCopy.bind(this);
  }

  handleOnCopy(theText) {
    //const { translate } = this.context;
    if (isDev) {
      console.log('Copied! -> ' + theText);
    }
    //console.log('Copied! ' + record.short_link);
    toast.info(
        //translate('resources.links.buttons.copy.confirm') + theText,
        translator.links.buttons.copy.confirm + theText,
        {
      position: toast.POSITION.BOTTOM_LEFT,
      className: 'dark-toast',
      progressClassName: 'transparent-progress',
      autoClose: 2000,
    });
  }

  normalizeRecord(record) {
    if (isDev) {
      console.log('record01-> ' + JSON.stringify(record));
    }
    if (record.simple_links && record.simple_links.length===0) {
      let simple_links = [];
      simple_links.push(record.short_link);
      record.simple_links = simple_links;
    }
    if (isDev) {
      console.log('record02-> ' + JSON.stringify(record));
    }
  }

  render() {
    const { record, isSingleItem } = this.props; // eslint-disable-line
    //this.normalizeRecord(record);

    return (
      <Card key={record._id} style={styles.card}>
        <CardContent>
          <Container fluid={true} style={{ alignItems: 'center' }}>
            <Row>
              <Col xs={12} md={12}>
                <div style={{ fontSize: 'xx-small', fontStyle: 'italic' }}>
                  {appConfig.web.baseUrl}...
                </div>
              </Col>
            </Row>
            <Row align={'center'}>
              <Col xs={12} md={12}>
                <SimpleLinks record={record} />
                {/* {(record.simple_links && record.simple_links.length>0) &&
                  <SimpleLinks record={record} />
                } */}
              </Col>
            </Row>

            <Row align={'center'}>
              <Col xs={12} md={12}>
                <QRCode
                  value={appConfig.web.baseUrl + record.short_link}
                  size={164}
                />
              </Col>
            </Row>

            <Row>
              <Col xs={12} md={12}>
                <div style={{ fontSize: 'xx-small', fontStyle: 'italic' }}>
                  <IconSchedule style={{ fontSize: 16 }} />
                  <TimeAgo
                    date={record.createdAt}
                    formatter={timeAgoFormatter_eng}
                  />
                </div>
              </Col>
            </Row>

            <Row>
              <Col xs={12} md={12}>
                <div style={{ fontSize: 'xx-small', fontStyle: 'italic' }}>
                  long_link:
                  <Button size="small"
                    target="_blank" rel="noopener noreferrer"
                    href={record.long_link}
                  >
                      <IconLink style={{ fontSize: 28 }} />
                  </Button>
                  <br />
                </div>
              </Col>
            </Row>
          </Container>
        </CardContent>

        <CardActions
          style={{
            textAlign: 'right',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <Container fluid={true}>
            <Row>

              <Col xs={4} md={4}>
                <CopyToClipboard
                  text={appConfig.web.baseUrl + record.short_link}
                  onCopy={this.handleOnCopy}
                >
                  <Button variant={"contained"}
                    size={"medium"} color={"secondary"}
                  >
                      {
                        //translate('resources.links.buttons.copy.name')
                        translator.links.buttons.copy.name
                      }
                      <IconCopy style={{ fontSize: 36, marginLeft: 4 }} />
                  </Button>
                </CopyToClipboard>
              </Col>
                <Col xs={4} md={4}>
                {!isSingleItem && ( // eslint-disable-line

                  <Button variant={"contained"}
                    size={"medium"} color={"secondary"}
                    href={'/links/' + record.short_link + '/stats'}
                  >
                      {
                        //translate('resources.links.buttons.stats.name')
                        translator.links.buttons.stats.name
                      }
                      <IconTimeline style={{ fontSize: 36, marginLeft: 4 }} />
                  </Button>
                )}
              </Col>
                <Col xs={4} md={4}>
                  <SocialShareButtons itemData={record} />
              </Col>


            </Row>
          </Container>
        </CardActions>
      </Card>
    );
  }
}

export default LinkMeta;
