// ulink-web-reactjs/src/links/LinkStats.jsx
import React, { Component } from 'react';
import PropTypes from 'prop-types';

import { Chart } from 'react-google-charts';
import Card from '@material-ui/core/Card';
import CardContent from '@material-ui/core/CardContent';

import Select from '@material-ui/core/Select';
import MenuItem from '@material-ui/core/MenuItem';

import { translator } from './LinkAssets';
import {isDev} from "../common/AppConfig";

const styles = {
  main: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    width: 800,
    //minHeight: 600,
    margin: '0.2em',
    display: 'inline-block',
    verticalAlign: 'top',
    textAlign: 'left',
  },
};

class StatsChart extends Component {

  render() {

    let itemKey = this.props.itemKey;
    let itemData = this.props.itemData;

    let statsData = [];
    statsData.push([itemKey, '']);
    if (itemData) {
      Object.keys(itemData).map(key2 => {
        statsData.push([key2, itemData[key2]]);
        return true;
      });
    }

    return (
      <Chart
        chartType="PieChart"
        data={statsData}
        options={{
          title: translator.links.buttons.stats.options[itemKey],
          pieHole: 0.4,
          is3D: true,
        }}
        graph_id="PieChart"
        width="100%"
        height="400px"
      />
    );
  }
}

StatsChart.propTypes = {
  itemKey: PropTypes.string,
  itemData: PropTypes.object,
};

class LinkStats extends Component {
  constructor(props) {
    super(props);
    this.state = {
      record: {},
      current: {},
    };

    this.prepareMenuOptions = this.prepareMenuOptions.bind(this);
    this.handleMenuSelection = this.handleMenuSelection.bind(this);
    this.handleUserInput = this.handleUserInput.bind(this);
  }

  componentWillMount() {
    let { record, current } = this.state;

    record.stats = this.props.record.stats; // eslint-disable-line
    //record._id = this.props.record._id;// eslint-disable-line

    if (!record.stats) {
      record.stats = {};
    }

    let itemKey = 'd_clicks';
    let itemData = record.stats[itemKey];
    current.itemKey = itemKey;
    current.itemData = itemData;

    this.setState({ record, current });

    /* if (isDev) {
      console.log('componentWillMount');
      //console.log('current -> ' + JSON.stringify(current));
      console.log('record -> ' + JSON.stringify(record));
      console.log('state -> ' + JSON.stringify(this.state));
    } */
  }

  handleMenuSelection = (event) => {
    this.handleUserInput(event.target.value);
  };
  handleUserInput(value) {
    let { record, current } = this.state;

    /* if (isDev) {
      console.log('handleUserInput');
      console.log('value -> ' + value);
      console.log('current -> ' + JSON.stringify(current));
      console.log('record -> ' + JSON.stringify(record));
    } */

    current['itemKey'] = value;
    current['itemData'] = record.stats[value];

    this.setState({ current });

    /* if (isDev) {
      console.log('handleUserInput');
      console.log('current -> ' + JSON.stringify(current));
    } */
  }

  prepareMenuOptions() {
    const { record, current } = this.state;

    if (isDev) {
      console.log("LinkStats.record: " + JSON.stringify(record));
    }

    const menuItems = Object.keys(record.stats).map(itemKey => (
      <MenuItem
        key={itemKey}
        value={itemKey}
      >
          {translator.links.buttons.stats.options[itemKey]}
      </MenuItem>
    ));

    return (
      <Select value={current.itemKey} onChange={this.handleMenuSelection}>
        {menuItems}
      </Select>
    );
  }

  render() {
    return (
      <Card key="one1" style={styles.card}>
        <CardContent>
          <div>{this.prepareMenuOptions()}</div>
          <div>
            <StatsChart {...this.state.current} />
          </div>
        </CardContent>
      </Card>
    );
  }
}

export default LinkStats;

// baet-web-vuejs/src/components/LinkStats.vue
<template>

  <v-card flat class="align-content-center">

    <v-card-text v-if="statsSelectItems.length>0">
      <v-flex xs12 sm6 d-flex>
        <v-select
            :items="statsSelectItems"
            v-model="statsKey"
            @input="updateChart"
            solo
        ></v-select>
      </v-flex>
    </v-card-text>

    <v-card-text>
      <!--
      <feathers-vuex-get
          service="stats"
          :id="linkId"
      >
        <div slot-scope="props" @load="this.linkStats=props.item">
          statsGet: {{props.item}}
        </div>
      </feathers-vuex-get>
      -->
      <feathers-vuex-find
          service="stats"
          :query="{_id: linkId}"
      >
        <div slot-scope="{ items }">
          {{ updateLinkStats(items) }}
        </div>
      </feathers-vuex-find>

    </v-card-text>

    <v-card-text>
      <v-flex d-flex>

        <h3 v-if="statsSelectItems.length===0">
          {{ $t('resources.links.nodata.stats') }}
        </h3>
        <google-chart v-else
            type="PieChart"
            :data="chartData"
            :options="chartOptions"
        />

      </v-flex>
    </v-card-text>

    <v-card-text v-if=isDev>
      linkStats...<br/> {{ linkStats }}
    </v-card-text>

  </v-card>
</template>

<script>
  import { isDev } from '@/app-config'; // eslint-disable-line
  import { GChart } from 'vue-google-charts';
  export default {
    name: "LinkStats",
    components: {
      'google-chart': GChart
    },
    props: {
      linkId: String,
    },
    data: () => ({
      isDev: isDev,
      linkStats: {},
      statsKey: 'd_clicks',
      statsData: {},
      statsSelectItems: [],
      chartData: [],
      chartOptions: {
        title: '',
        pieHole: 0.4,
        is3D: true
      },
    }),
    watch: {
      linkStats: function () {
        /*if (this.isDev) {
          console.log("watch- linkStats: " + JSON.stringify(this.linkStats))
        }*/
        if (this.linkStats) {
          this.prepareChartData()
        }
      },
      statsKey: function() {
        this.chartOptions.title = this.$t('resources.links.buttons.stats.options.'+this.statsKey);
      }
    },
    methods: {
      updateChart: function() {
        /*if (isDev) {
          console.log("updateChart: " + this.statsKey)
        }*/
        this.chartOptions.title = this.$t('resources.links.buttons.stats.options.'+this.statsKey);
        this.statsData = this.linkStats['stats'][this.statsKey];
        this.chartData = [];
        this.chartData.push([this.statsKey, '']);
        Object.keys(this.statsData).map(key2 => {
          this.chartData.push([key2, this.statsData[key2]]);
          return true;
        });
      },
      updateLinkStats: function(items) {
        items.forEach((item) => {
          /*if (this.isDev) {
            console.log("item: " + JSON.stringify(item));
          }*/
          this.linkStats = item;
        });
      },
      prepareChartData: function() {
        let menuItems = Object.keys(this.linkStats['stats']);
        for (let menuItem of menuItems) {
          let item = {
            value: menuItem,
            text: this.$t('resources.links.buttons.stats.options.'+menuItem)
          };
          this.statsSelectItems.push(item);
        }
        if (this.statsKey===undefined || this.statsKey==='') {
          this.statsKey = menuItems[0];
          //this.statsKey = 'd_clicks';
        }

        this.updateChart();
      },
    },
  }
</script>

<style scoped>

</style>
